databases:
  - name: form-db
    databaseName: form_db
    user: user

services:
  - type: web
    name: collab-form-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: form-db
          property: connectionString
    autoDeploy: true